### ISSUE TITLE
Update Components namespaces to new structure for Components 2.x/3.x

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/particle#200]
@bmartinez287 
[warning] Components 8.x-1.x API is deprecated in components:8.x-2.0 and is removed from components:3.0.0. Update the particle.info.yml file to replace the component-libraries.[namespace].paths data with components.namespaces.[namespace]. 
- docroot/themes/custom/particle/apps/drupal-default/particle_theme/particle.info.yml
- See https://www.drupal.org/node/3082817
   - https://www.drupal.org/docs/contributed-modules/components/registering-twig-namespaces

So it sounds like this:
```
component-libraries:
  protons:
    paths: []
  atoms:
    paths:
      - ../../../dist/app-drupal/assets/atomic/_patterns/01-atoms
  molecules:
    paths:
      - ../../../dist/app-drupal/assets/atomic/_patterns/02-molecules
  organisms:
    paths:
      - ../../../dist/app-drupal/assets/atomic/_patterns/03-organisms
  templates:
    paths: []
  pages:
    paths: []
```
... should change to:
```
components:
  namespaces:
    protons: []
    atoms: ../../../dist/app-drupal/assets/atomic/_patterns/01-atoms
    molecules: ../../../dist/app-drupal/assets/atomic/_patterns/02-molecules
    organisms: ../../../dist/app-drupal/assets/atomic/_patterns/03-organisms
    templates: []
    pages: []
```
